window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
window.isSafari=!1;if(/^((?!chrome|android).)*safari/i.test(navigator.userAgent)){window.isSafari=!0}
window.isSafariVersion='';if(window.isSafari){var version=(navigator.appVersion).match(/Version\/(\d+)\.(\d+)\.?(\d+)? Safari/);if(version!==null){window.isSafariVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});menu.addEventListener('menuOverflow',function(){t450_checkSize(recid)});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed')}else{menu.classList.remove('t450__overflowed')}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t331_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return!1;rec.setAttribute('data-animationappear','off');rec.style.opacity='1';var currentBlock=rec.querySelector('.t-popup');var currentHook=currentBlock?currentBlock.getAttribute('data-tooltip-hook'):'';var currentAnalitics=currentBlock?currentBlock.getAttribute('data-track-popup'):'';if(!currentHook)return!1;t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(currentHook)});document.addEventListener('click',function(e){var href=e.target.closest('a[href="'+currentHook+'"]');if(href){e.preventDefault();t331_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});if(currentAnalitics){var virtTitle=currentHook;if(virtTitle.substring(0,7)==='#popup:')virtTitle=virtTitle.substring(7);Tilda.sendEventToStatistics(currentAnalitics,virtTitle)}}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,currentHook)})}
function t331_setHeight(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var videoCarrier=rec.querySelector('.t331__video-carier');var carrierParent=videoCarrier?videoCarrier.parentNode:null;var videoWidth=videoCarrier?videoCarrier.getAttribute('data-video-width'):'0';var videoHeight=videoCarrier?videoCarrier.getAttribute('data-video-height'):'0';if(videoHeight.indexOf('vh')!==-1){videoHeight=parseInt(videoHeight,10)*window.innerHeight/100}else{videoHeight=parseInt(videoHeight,10)}
var ratio=videoHeight/(parseInt(videoWidth,10)||1);var videoCurrentWidth=videoCarrier?videoCarrier.offsetWidth:0;var calculatedHeight=videoCurrentWidth*ratio;if(videoCarrier)videoCarrier.style.height=calculatedHeight+'px';if(carrierParent)carrierParent.style.height=calculatedHeight+'px'}
function t331_showPopup(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var popup=rec.querySelector('.t-popup');var videoContainer=rec.querySelector('.t331__youtube');var videoCarrier=rec.querySelector('.t331__video-carier');var isVideoCarrierExist=!!videoCarrier.querySelector('iframe');if(isVideoCarrierExist)return;var videoID=videoContainer?videoContainer.getAttribute('data-content-popup-video-url-youtube'):'';if(videoID)videoID=videoID.replace('https://www.youtube.com/shorts/','');var videoURL=videoID?'https://www.youtube.com/embed/'+videoID:'';if(videoCarrier){var iframe=document.createElement('iframe');iframe.id='youtubeiframe'+recid;iframe.classList.add('t331__iframe');iframe.width='100%';iframe.height='100%';iframe.src=videoURL+(videoURL.indexOf('?')!==-1?'&':'?')+'autoplay=1&rel=0';iframe.frameBorder='0';iframe.setAttribute('allowfullscreen','');videoCarrier.insertAdjacentElement('beforeend',iframe)}
if(popup)popup.style.display='block';t331_setHeight(recid);setTimeout(function(){var popupContainer=popup?popup.querySelector('.t-popup__container'):null;if(popupContainer)popupContainer.classList.add('t-popup__container-animated');if(popup)popup.classList.add('t-popup_show');t_onFuncLoad('t_popup__trapFocus',function(){t_popup__trapFocus(popup)})},50);document.body.classList.add('t-body_popupshowed');document.body.classList.add('t331__body_popupshowed');if(popup){popup.addEventListener('click',function(e){if(e.target===popup)t331_popup_close(recid)})}
var popupClose=popup?popup.querySelector('.t-popup__close'):null;if(popupClose){popupClose.addEventListener('click',function(){t331_popup_close(recid)})}
document.addEventListener('keydown',function(e){if(e.keyCode===27)t331_popup_close(recid)})}
function t331_popup_close(recid){document.body.classList.remove('t-body_popupshowed');document.body.classList.remove('t331__body_popupshowed');var rec=document.getElementById('rec'+recid);if(!rec)return!1;var popup=rec.querySelector('.t-popup');var videoCarrier=rec.querySelector('.t331__video-carier');if(popup)popup.classList.remove('t-popup_show');t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){if(videoCarrier)videoCarrier.innerHTML='';if(popup&&!popup.classList.contains('t-popup_show')){popup.style.display='none'}},300)}
function t331_sendPopupEventToStatistics(popupname){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupname.substring(0,7)==='#popup:'){popupname=popupname.substring(7)}
virtPage+=popupname;virtTitle+=popupname;if(ga){if(window.mainTracker!=='tilda'){ga('send',{'hitType':'pageview','page':virtPage,'title':virtTitle})}}
if(window.mainMetrika>''&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(){var target=event.target;var href=target.closest('a[href*="#"]')?target.closest('a[href*="#"]'):!1;if(!href)return;var arrHref=href.href.split('#');if(decodeURI('#'+arrHref[1])!==popupTooltipHook)return;event.preventDefault();t702_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t702__lazyLoad();if(analitics){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup(recId)});popupCloseBtn.addEventListener('click',function(){t702_closePopup(recId)});if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recId);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){documentBody.classList.add('t-body_popupshowed')},300)}}})}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup(recId)}
popup.addEventListener('tildamodal:show'+popupTooltipHook,function(){document.addEventListener('keydown',t702_escClosePopup)});popup.addEventListener('tildamodal:close'+popupTooltipHook,function(){document.removeEventListener('keydown',t702_escClosePopup)})}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var range=rec.querySelector('.t-range');var documentBody=document.body;if(range)t702__triggerEvent(range,'popupOpened');t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
t702__lazyLoad();t702__triggerEvent(popup,'tildamodal:show'+popupTooltipHook)}
function t702_closePopup(recId){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAll=document.querySelectorAll('.t-popup_show:not(.t-feed__post-popup)');if(popupAll.length==1){document.body.classList.remove('t-body_popupshowed')}else{var newPopup=[];for(var i=0;i<popupAll.length;i++){if(popupAll[i].getAttribute('data-tooltip-hook')===popupTooltipHook){popupAll[i].classList.remove('t-popup_show');newPopup.push(popupAll[i])}}
if(newPopup.length===popupAll.length){document.body.classList.remove('t-body_popupshowed')}}
popup.classList.remove('t-popup_show');document.body.classList.remove('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);t702__triggerEvent(popup,'tildamodal:close'+popupTooltipHook)}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t827_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var grid=rec.querySelector('.t827__grid');var sizer=rec.querySelector('.t827__grid-sizer');var items=rec.querySelectorAll('.t827__grid-item');var images=rec.querySelectorAll('.t827__grid img');var overlayList=rec.querySelectorAll('.t827__overlay');var sizerWidth=sizer?sizer.offsetWidth||parseInt(window.getComputedStyle(sizer).width,10):0;if(window.getComputedStyle(rec).display==='none'){grid.setAttribute('data-hidden-tab','y')}
t827_reverse(grid);Array.prototype.forEach.call(images,function(img){img.addEventListener('load',function(){t827_initMasonry(rec,recid,grid);setTimeout(function(){t827_showOverlay(overlayList,items)},500)})});Array.prototype.forEach.call(overlayList,function(overlay){if(overlay.classList.contains('t827__overlay_preview')){setTimeout(function(){t827_showOverlay([overlay],items)},1000)}});t827_initMasonry(rec,recid,grid);window.addEventListener('resize',t_throttle(function(){if(typeof window.noAdaptive!=='undefined'&&window.noAdaptive===!0&&window.isMobile){return}
t827_initMasonry(rec,recid,grid);t827_calcColumnWidth(rec,sizerWidth,grid,sizer,items)}));if(typeof jQuery!=='undefined'){$(rec).find('.t827').bind('displayChanged',function(e){t827_initMasonry(rec,recid,grid,e.type);t827_calcColumnWidth(rec,sizerWidth,grid,sizer,items)})}else{var wrapper=rec.querySelector('.t827');wrapper.addEventListener('displayChanged',function(e){t827_initMasonry(rec,recid,grid,e.type);t827_calcColumnWidth(rec,sizerWidth,grid,sizer,items)})}
setTimeout(function(){t827_calcColumnWidth(rec,sizerWidth,grid,sizer,items)})}
function t827_reverse(grid){if(grid&&grid.classList.contains('t827__grid_reverse')){for(var i=grid.childElementCount-2;i>=0;i--){grid.appendChild(grid.children[i])}}}
function t827_initMasonry(rec,recid,grid,eventType){var gutterElement=rec.querySelector('.t827__gutter-sizer');var gutterWidth;if(gutterElement&&(gutterElement.offsetWidth===40||window.getComputedStyle(gutterElement).width==='40px')){gutterWidth=39}else{gutterWidth='#rec'+recid+' .t827__gutter-sizer'}
t_onFuncLoad('imagesLoaded',function(){if(eventType==='displayChanged'&&grid.getAttribute('data-hidden-tab')==='y'){grid.style.opacity='0';imagesLoaded(grid,function(){if(grid.style.opacity==='0'){grid.style.opacity=''}
grid.removeAttribute('data-hidden-tab')});setTimeout(function(){if(grid.style.opacity==='0'){grid.style.opacity=''}
grid.removeAttribute('data-hidden-tab')},3000);new Masonry(grid,{columnWidth:'#rec'+recid+' .t827__grid-sizer',itemSelector:'#rec'+recid+' .t827__grid-item',gutter:gutterWidth,isFitWidth:!0,transitionDuration:0,})}else{imagesLoaded(grid,function(){new Masonry(grid,{columnWidth:'#rec'+recid+' .t827__grid-sizer',itemSelector:'#rec'+recid+' .t827__grid-item',gutter:gutterWidth,isFitWidth:!0,transitionDuration:0,})})}})}
function t827_showOverlay(overlayList,items){if(window.innerWidth>=1024){Array.prototype.forEach.call(overlayList,function(overlay){overlay.style.display='block'})}else{Array.prototype.forEach.call(items,function(item){item.addEventListener('click',function(){var currentOverlay=item.querySelector('.t827__overlay');if(currentOverlay){if(currentOverlay.style.opacity==='0'){Array.prototype.forEach.call(overlayList,function(overlay){if(overlay===currentOverlay){overlay.style.opacity='1'}else{overlay.style.opacity='0'}})}else{currentOverlay.style.opacity='0'}}})})}}
function t827_calcColumnWidth(rec,sizerWidth,grid,sizer,items){var isRecHidden=window.getComputedStyle(rec).display==='none';if(isRecHidden){rec.style.setProperty('display','block','important')}
var container=rec.querySelector('.t827__container');var firstItem=rec.querySelector('.t827__grid-item');var gutterElement=rec.querySelector('.t827__gutter-sizer');var containerWidthViaPadding=container?container.offsetWidth||parseInt(window.getComputedStyle(container).width,10):0;var containerPaddingLeft=container?window.getComputedStyle(container).getPropertyValue('padding-left'):'0';var containerPaddingLeftValue=parseInt(containerPaddingLeft,10)||0;var containerPaddingRight=container?window.getComputedStyle(container).getPropertyValue('padding-right'):'0';var containerPaddingRightValue=parseInt(containerPaddingRight,10)||0;var containerWidth=containerWidthViaPadding-(containerPaddingLeftValue+containerPaddingRightValue);var itemWidth=firstItem?firstItem.offsetWidth||parseInt(window.getComputedStyle(firstItem).width,10):0;var gutterSizerWidth=gutterElement?gutterElement.offsetWidth||parseInt(window.getComputedStyle(gutterElement).width,10):0;if(gutterElement&&gutterSizerWidth===40)gutterSizerWidth=39;if(isRecHidden)rec.style.display='';var columnAmount=Math.round(containerWidth/sizerWidth);var newSizerWidth=((containerWidth-gutterSizerWidth*(columnAmount-1))/columnAmount);if(containerWidth>=itemWidth){if(sizer)sizer.style.width=newSizerWidth+'px';Array.prototype.forEach.call(items,function(item){item.style.width=newSizerWidth+'px'})}else{if(grid)grid.style.width='100%';if(sizer)sizer.style.width='100%';Array.prototype.forEach.call(items,function(item){item.style.width=newSizerWidth+'px'})}}
function t585_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var accordion=rec.querySelectorAll('.t585__accordion')[0];var headers=rec.querySelectorAll('.t585__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordionScroll;if(accordion){accordionScroll=accordion.getAttribute('data-scroll-to-expanded');accordion=accordion.getAttribute('data-accordion')}else{accordion='false';accordionScroll='false'}
for(var i=0;i<headers.length;i++){headers[i].addEventListener('click',function(){var element=this;var container=element.nextElementSibling;var triggerButton=element.querySelector('.t585__trigger-button');var activeHeight=0;var isAccordionDown=!1;var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);container.hidden=isExpanded;if(element.classList.contains('t585__opened')){element.classList.remove('t585__opened');t585_accordionHide(container)}else{if(accordionScroll==='true'&&accordion==='true'){activeHeight=t585__getOldAction(rec);isAccordionDown=t585__getAccordionPosition(headers,element)}
if(accordion==='true')t585_accordionAllHide(headers);element.classList.add('t585__opened');container.style.display='block';var height=container.scrollHeight;container.style.maxHeight='0px';setTimeout(function(){container.style.maxHeight=height+'px';if(accordionScroll==='true'){t585__calcHeight(element,container,activeHeight,isAccordionDown)}},0)}
if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}}
function t585_accordionAllHide(headers){for(var i=0;i<headers.length;i++){var elementHide=headers[i];elementHide.classList.remove('t585__opened');t585_accordionHide(elementHide.nextElementSibling)}}
function t585_accordionHide(container){if(!container.style.maxHeight)container.style.maxHeight=container.scrollHeight+'px';setTimeout(function(){container.style.maxHeight='0px'},0)}
function t585__getOldAction(rec){var activeHeader=rec.querySelector('.t585__opened');var activeHeight=0;if(activeHeader)var activeContainer=activeHeader.nextElementSibling;if(activeContainer)activeHeight=activeContainer.offsetHeight;return activeHeight}
function t585__getAccordionPosition(headers,element){var oldIndex;var newIndex;for(var i=0;i<headers.length;i++){var header=headers[i];if(header.classList.contains('t585__opened'))oldIndex=i;if(header===element)newIndex=i}
return oldIndex<newIndex?!0:!1}
function t585__calcHeight(element,container,activeHeight,isAccordionDown){var windowHeight=window.innerHeight;var windowScroll=window.scrollY;var containerHeight=container.scrollHeight;var accordionHeight=containerHeight+element.offsetHeight;var elementTopOffset=element.getBoundingClientRect().top+windowScroll;var target=isAccordionDown?elementTopOffset-activeHeight:elementTopOffset;var accordionBottomLine=target+accordionHeight;var windowBottomLine=windowScroll+windowHeight;if(target<windowScroll||accordionHeight>windowHeight||accordionBottomLine>windowBottomLine){t585__scroll(target)}}
function t585__scroll(target){var duration=400;var start=(window.pageYOffset||document.documentElement.scrollTop)-(document.documentElement.clientTop||0);var change=target-start;var currentTime=0;var increment=16;document.body.setAttribute('data-scrollable','true');function t585__easeInOutCubic(currentTime){if((currentTime/=duration/2)<1){return change/2*currentTime*currentTime*currentTime+start}else{return change/2*((currentTime-=2)*currentTime*currentTime+2)+start}}
function t585__animateScroll(){currentTime+=increment;window.scrollTo(0,t585__easeInOutCubic(currentTime));if(currentTime<duration){setTimeout(t585__animateScroll,increment)}else{document.body.removeAttribute('data-scrollable')}}
t585__animateScroll()}